In [1]:
using Distributions

In [42]:
cost = [193;226;240;244;257;260;274;297;350;420]
y = cost

10-element Array{Int64,1}:
 193
 226
 240
 244
 257
 260
 274
 297
 350
 420

In [43]:
quantity = [1;2;3;4;5;6;7;8;9;10]

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [44]:
quantity_sq = quantity .^2

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [45]:
quantity_cb = quantity .^3

10-element Array{Int64,1}:
    1
    8
   27
   64
  125
  216
  343
  512
  729
 1000

In [47]:
# Model 6
X_6 = [ ones(length(cost)) quantity ]
β_6 = inv(X_6'X_6) * X_6' * y

2-element Array{Float64,1}:
 166.467 
  19.9333

In [48]:
# Model 7
X_7 = [ ones(length(cost)) quantity quantity_sq ]
β_7 = inv(X_7'X_7) * X_7' * y

3-element Array{Float64,1}:
 222.383  
  -8.025  
   2.54167

In [49]:
# Model 8
X_8 = [ ones(length(cost)) quantity quantity_sq quantity_cb ]
β_8 = inv(X_8'X_8) * X_8' * y

4-element Array{Float64,1}:
 141.767   
  63.4777  
 -12.9615  
   0.939588

In [50]:
model_headers = ["" "(6)" "(7)" "(8)"]
tb_c1 = ["intercept" β_6[1] β_7[1] β_8[1]]
tb_c2 = ["Qi" β_6[2] β_7[2] β_8[2]]
tb_c3 = ["Qi_sq" "-" β_7[3] β_8[3]]
tb_c4 = ["Qi_cb" "-" "-" β_8[4]]
table = [model_headers; tb_c1; tb_c2; tb_c3; tb_c4]

5×4 Array{Any,2}:
 ""              "(6)"     "(7)"      "(8)"  
 "intercept"  166.467   222.383    141.767   
 "Qi"          19.9333   -8.025     63.4777  
 "Qi_sq"         "-"      2.54167  -12.9615  
 "Qi_cb"         "-"       "-"       0.939588

In [62]:
# Model 6
SSR_6 = sum((y-X_6*β_6).^2)
SSE_6 = sum((X_6*β_6-mean(y)).^2)
SST_6 = sum((y-mean(y)).^2)
R2_6 = SSE_6 / SST_6

0.840890920548925

In [63]:
# Model 7
SSR_7 = sum((y-X_7*β_7).^2)
SSE_7 = sum((X_7*β_7-mean(y)).^2)
SST_7 = sum((y-mean(y)).^2)
R2_7 = SSE_7 / SST_7

0.9283886866634651

In [65]:
# Model 8
SSR_8 = sum((y-X_8*β_8).^2)
SSE_8 = sum((X_8*β_8-mean(y)).^2)
SST_8 = sum((y-mean(y)).^2)
R2_8 = SSE_8 / SST_8

0.9983391737709674

In [66]:
row_R2 = ["R2" R2_6 R2_7 R2_8]
table = [table; row_R2]

6×4 Array{Any,2}:
 ""              "(6)"       "(7)"       "(8)"  
 "intercept"  166.467     222.383     141.767   
 "Qi"          19.9333     -8.025      63.4777  
 "Qi_sq"         "-"        2.54167   -12.9615  
 "Qi_cb"         "-"         "-"        0.939588
 "R2"           0.840891    0.928389    0.998339

In [67]:
R2a_6 = 1 - (1-R2_6)*(10-1)/(10-1-1)
R2a_7 = 1 - (1-R2_7)*(10-1)/(10-2-1)
R2a_8 = 1 - (1-R2_8)*(10-1)/(10-3-1)
row_R2a = ["R2a" R2a_6 R2a_7 R2a_8]
table = [table; row_R2a]

7×4 Array{Any,2}:
 ""              "(6)"       "(7)"       "(8)"  
 "intercept"  166.467     222.383     141.767   
 "Qi"          19.9333     -8.025      63.4777  
 "Qi_sq"         "-"        2.54167   -12.9615  
 "Qi_cb"         "-"         "-"        0.939588
 "R2"           0.840891    0.928389    0.998339
 "R2a"          0.821002    0.907928    0.997509