In [1]:
using Combinatorics

# Northwest Corner Method

In [91]:
function NCM(in_S, in_D, in_C)
    S, D, C = copy(in_S), copy(in_D), copy(in_C)
    
    #print demand/supply
    println("Total Supply: $(sum(S))", "\n", "Total Demand: $(sum(D))")
    
    #compare supply and demand
    if sum(S) > sum(D) 
        D = [D; sum(S)-sum(D)]
        C = [C zeros(size(S)[1])]
    elseif sum(S) < sum(D) 
        S = [S; sum(D)-sum(S)]
        C = [C; zeros(size(D)[1])']
    end
    
    #get m and n
    m, n = size(C)
    
    #get X vector
    X = fill(NaN, m, n)
    
    #start algorithm
    i, j = 1, 1
    while count(.!isnan.(X)) < m + n - 1
        x = min(S[i], D[j])
        X[i,j] = x
        if x == S[i]
            i += 1
            D[j] -= x
        else
            j += 1
            S[i] -= x
        end
    end
    
    return X
end

NCM (generic function with 1 method)

# Minimum-Cost Method

In [3]:
function MCM(in_S, in_D, in_C)
    S, D, C = copy(in_S), copy(in_D), copy(in_C)
    
    #print demand/supply
    println("Total Supply: $(sum(S))", "\n", "Total Demand: $(sum(D))")
    
    #compare supply and demand
    if sum(S) > sum(D) 
        D = [D; sum(S)-sum(D)]
        C = [C zeros(size(S)[1])]
    elseif sum(S) < sum(D) 
        S = [S; sum(D)-sum(S)]
        C = [C; zeros(size(D)[1])']
    end
    
    #get m and n
    m, n = size(C)
    
    #get X vector
    X = fill(NaN, m, n)
    
    #start algorithm
    while count(.!isnan.(X)) < m + n - 1
        #get min cost
        i, j = ind2sub(size(C),indmin(C))
        
        #get entry value
        x = min(S[i], D[j])
        X[i,j] = x
        
        #adjust supply/demand remaining and remove min cost
        if S[i] == D[j] 
            if count(.!isnan.(C[i,:])) >= count(.!isnan.(C[:,j]))
                S[i] -= x
                C[:,j] .= NaN
            else
                D[j] -= x
                C[i,:] .= NaN
            end
        elseif x == S[i]
            D[j] -= x
            C[i,:] .= NaN        
        else
            S[i] -= x
            C[:,j] .= NaN 
        end
    end
    
    return X
end

MCM (generic function with 1 method)

# Vogel Method

In [4]:
function Vogel(in_S, in_D, in_C)
    S, D, C = copy(in_S), copy(in_D), copy(in_C)
    
    #print demand/supply
    println("Total Supply: $(sum(S))", "\n", "Total Demand: $(sum(D))")
    
    #compare supply and demand
    if sum(S) > sum(D) 
        D = [D; sum(S)-sum(D)]
        C = [C zeros(size(S)[1])]
    elseif sum(S) < sum(D) 
        S = [S; sum(D)-sum(S)]
        C = [C; zeros(size(D)[1])']
    end
    
    #get m and n
    m, n = size(C)
    
    #get X vector
    X = fill(NaN, m, n)
    
    #start algorithm
    while count(.!isnan.(X)) < m + n - 1
        
        r_dif = sort(C, 2)[:,2]-sort(C, 2)[:,1]
        d_dif = sort(C, 1)[2,:]-sort(C, 1)[1,:]
                
        if count(.!isnan.(r_dif)) >= 1 && count(.!isnan.(d_dif)) >= 1
            if findmax(r_dif)[1] >= findmax(d_dif)[1]
                i = indmax(r_dif)
                j = indmin(C[i,:])
            else
                j = indmax(d_dif)
                i = indmin(C[:,j])
            end
        elseif count(.!isnan.(r_dif)) == 0 && count(.!isnan.(d_dif)) >= 1
            j = indmax(d_dif)
            i = indmin(C[:,j])
        elseif count(.!isnan.(d_dif)) == 0 && count(.!isnan.(r_dif)) >= 1
            i = indmax(r_dif)
            j = indmin(C[i,:])
        else
            i, j = ind2sub(size(C),indmin(C))
        end

        #get entry value
        x = min(S[i], D[j])
        X[i,j] = x
        
        #adjust supply/demand remaining and remove min cost
        if S[i] == D[j] 
            if count(.!isnan.(C[i,:])) >= count(.!isnan.(C[:,j]))
                S[i] -= x
                D[j] -= x
                C[:,j] .= NaN
            else
                S[i] -= x
                D[j] -= x
                C[i,:] .= NaN
            end
        elseif x == S[i]
            S[i] -= x
            D[j] -= x
            C[i,:] .= NaN        
        else
            S[i] -= x
            D[j] -= x
            C[:,j] .= NaN 
        end
    end
    
    return X
end

Vogel (generic function with 1 method)

# General Solver

In [5]:
function GeneralSolver(in_S, in_D, in_C)
    S, D, C = copy(in_S), copy(in_D), copy(in_C)
    
    #print demand/supply
    println("Total Supply: $(sum(S))", "\n", "Total Demand: $(sum(D))")
    
    #compare supply and demand
    if sum(S) > sum(D) 
        D = [D; sum(S)-sum(D)]
        C = [C zeros(size(S)[1])]
    elseif sum(S) < sum(D) 
        S = [S; sum(D)-sum(S)]
        C = [C; zeros(size(D)[1])']
    end
    
    #get m and n
    m, n = size(C)
    
    #define constraint table
    a1 = zeros(0)
    a2 = zeros(0)
    for i in 1:m
        Z = zeros(m,n)
        Z[i,:] .= 1
        a1 = [a1; Z'] 
        a2 = [a2; eye(n)]
    end
    
    A = [a1'; a2']
    b = [S; D]
    c = vec(C')'
    
    var_names = String[]
    for i in 1:m, j in 1:n
        push!(var_names, "x_$(i)$(j)")
    end
    
    A = A[2:end,:]
    b = b[2:end]

    #output
    output = Dict()
    
    counter = 0
    for basic_pair in collect(combinations(1:length(var_names), m+n-1))
        counter += 1
        
        B = zeros(0)
        for t in 1:m+n-1 
            B = [B; A[:,basic_pair[t]]'] 
        end
        B = B'
        
        if det(B) != 0
            x_B = inv(B)*b
            
            var_x = String[]
            for var_i in basic_pair push!(var_x, var_names[var_i]) end
            
            c_B = zeros(0)
            for t in 1:m+n-1 c_B = [c_B; c[basic_pair[t]]] end
            
            c_B = c_B'
            
            z = c_B*x_B
            
            if "Cost" in keys(output)
                if output["Cost"] > z && sum(abs.(x_B)) == sum(x_B)
                    output["Cost"] = z
                    output["Basic Pair"] = var_x
                    output["Value"] = x_B
                end
            elseif sum(abs.(x_B)) == sum(x_B)
                output["Cost"] = z
                output["Basic Pair"] = var_x
                output["Value"] = x_B 
            end
                      
        end
    end
    println("\n", "Iterations: $(counter)", "\n")
    return output, ["_" "_"; "Cost" output["Cost"]; "_" "_"; output["Basic Pair"] output["Value"]; "_" "_"]
end

GeneralSolver (generic function with 1 method)

# Exercises

### 2

In [6]:
ex2_S = [10, 10, 20]
ex2_D = [15, 10, 5, 10]
ex2_C = [4 6 9 2; 5 2 4 8; 7 4 9 12];

### 3

In [7]:
ex3_S = [50, 50]
ex3_D = [20, 20, 20]
ex3_C = [800 700 400; 600 800 500];

In [8]:
NCM(ex3_S,ex3_D,ex3_C)

Total Supply: 100
Total Demand: 60


2×4 Array{Float64,2}:
  20.0   20.0  10.0  NaN  
 NaN    NaN    10.0   40.0

In [9]:
MCM(ex3_S,ex3_D,ex3_C)

Total Supply: 100
Total Demand: 60


2×4 Array{Float64,2}:
 NaN    NaN    10.0   40.0
  20.0   20.0  10.0  NaN  

In [10]:
Vogel(ex3_S,ex3_D,ex3_C)

Total Supply: 100
Total Demand: 60


2×4 Array{Float64,2}:
 10.0   20.0   20.0  NaN  
 10.0  NaN    NaN     40.0

In [11]:
GeneralSolver(ex3_S,ex3_D,ex3_C)[1]

Total Supply: 100
Total Demand: 60

Iterations: 56



Dict{Any,Any} with 3 entries:
  "Cost"       => 34000.0
  "Value"      => [20.0, 20.0, 10.0, 20.0, 30.0]
  "Basic Pair" => String["x_12", "x_13", "x_14", "x_21", "x_24"]

### 4

In [12]:
ex4_S = [400, 600, 400, 600, 1000]
ex4_D = [600, 1000, 800]
M = 10000; ex4_C = [31 29 32 28 29; 45 41 46 42 43; 38 35 40 copy(M) copy(M)]';

In [13]:
NCM(ex4_S, ex4_D, ex4_C)

Total Supply: 3000
Total Demand: 2400


5×4 Array{Float64,2}:
 400.0  NaN    NaN    NaN  
 200.0  400.0  NaN    NaN  
 NaN    400.0  NaN    NaN  
 NaN    200.0  400.0  NaN  
 NaN    NaN    400.0  600.0

In [14]:
MCM(ex4_S, ex4_D, ex4_C)

Total Supply: 3000
Total Demand: 2400


5×4 Array{Float64,2}:
 NaN     NaN    NaN    400.0
   0.0   NaN    400.0  200.0
 NaN       0.0  400.0  NaN  
 600.0   NaN    NaN    NaN  
 NaN    1000.0  NaN    NaN  

In [15]:
Vogel(ex4_S, ex4_D, ex4_C)

Total Supply: 3000
Total Demand: 2400


5×4 Array{Float64,2}:
 NaN     NaN    200.0  200.0
 NaN       0.0  600.0  NaN  
 NaN     NaN    NaN    400.0
 600.0   NaN    NaN    NaN  
   0.0  1000.0  NaN    NaN  

In [16]:
ex4_sol = GeneralSolver(ex4_S, ex4_D, ex4_C)

Total Supply: 3000
Total Demand: 2400

Iterations: 125970



(Dict{Any,Any}(Pair{Any,Any}("Cost", 88400.0),Pair{Any,Any}("Value", [0.0, 0.0, 200.0, 200.0, 600.0, 400.0, 600.0, 1000.0]),Pair{Any,Any}("Basic Pair", String["x_11", "x_12", "x_13", "x_14", "x_23", "x_34", "x_41", "x_52"])), Any["_" "_"; "Cost" 88400.0; … ; "x_52" 1000.0; "_" "_"])

In [17]:
ex4_sol[2]

12×2 Array{Any,2}:
 "_"          "_"
 "Cost"  88400.0 
 "_"          "_"
 "x_11"      0.0 
 "x_12"      0.0 
 "x_13"    200.0 
 "x_14"    200.0 
 "x_23"    600.0 
 "x_34"    400.0 
 "x_41"    600.0 
 "x_52"   1000.0 
 "_"          "_"

In [48]:
ex4_sol[1]

Dict{Any,Any} with 3 entries:
  "Cost"       => 88400.0
  "Value"      => [0.0, 0.0, 200.0, 200.0, 600.0, 400.0, 600.0, 1000.0]
  "Basic Pair" => String["x_11", "x_12", "x_13", "x_14", "x_23", "x_34", "x_41"…

### 5

In [53]:
function ex5()
    
    output = Dict()
    
    for Δ in 0:(sum([60, 80, 40])-sum([40, 60, 20]))
        ex5_S = [60, 80, 40]
        ex5_D = [40, 60, 80-Δ, 0+Δ]
        ex5_C = -[800 700 500 200; 500 200 100 300; 600 400 300 500]
        
        if "Cost" in keys(output)
            new_output = GeneralSolver(ex5_S, ex5_D, ex5_C)[1]
            if new_output["Cost"] < output["Cost"]
                output = new_output
            elseif new_output["Cost"] == output["Cost"]
                println(new_output["Value"])
                println(new_output["Basic Pair"])
            end
        else
            output = GeneralSolver(ex5_S, ex5_D, ex5_C)[1]
        end
    end
    
    return output
end

ex5 (generic function with 1 method)

In [55]:
ex5()

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Demand: 180

Iterations: 924

Total Supply: 180
Total Dema

Dict{Any,Any} with 3 entries:
  "Cost"       => -90000.0
  "Value"      => [0.0, 60.0, 40.0, 20.0, 20.0, 40.0]
  "Basic Pair" => String["x_11", "x_12", "x_21", "x_23", "x_24", "x_34"]

_________

_________

### 6

In [64]:
ex6_S = [20, 16, 14, 20, 62]
ex6_D = [48, 60, 64, 28]
M = 10000
ex6_C = [400 450 350 copy(M);
    1350 copy(M) 750 450;
    850 500 900 550;
    700 copy(M) 700 900;
    450 650 500 1250];

In [65]:
NCM(ex6_S, ex6_D, ex6_C)

Total Supply: 132
Total Demand: 200


6×4 Array{Float64,2}:
  20.0  NaN    NaN    NaN  
  16.0  NaN    NaN    NaN  
  12.0    2.0  NaN    NaN  
 NaN     20.0  NaN    NaN  
 NaN     38.0   24.0  NaN  
 NaN    NaN     40.0   28.0

In [66]:
MCM(ex6_S, ex6_D, ex6_C)

Total Supply: 132
Total Demand: 200


6×4 Array{Float64,2}:
 NaN    NaN     20.0  NaN  
 NaN    NaN    NaN     16.0
 NaN     14.0  NaN    NaN  
 NaN      8.0  NaN     12.0
 NaN     18.0   44.0  NaN  
  48.0   20.0  NaN    NaN  

In [67]:
Vogel(ex6_S, ex6_D, ex6_C)

Total Supply: 132
Total Demand: 200


6×4 Array{Float64,2}:
 NaN    NaN     20.0  NaN  
 NaN    NaN    NaN     16.0
 NaN    NaN     10.0    4.0
 NaN    NaN     20.0  NaN  
  48.0  NaN     14.0  NaN  
 NaN     60.0  NaN      8.0

In [24]:
ex6_sol = GeneralSolver(ex6_S, ex6_D, ex6_C);

Total Supply: 132
Total Demand: 200

Iterations: 1307504



In [25]:
ex6_sol[2]

13×2 Array{Any,2}:
 "_"          "_"
 "Cost"  63800.0 
 "_"          "_"
 "x_13"     20.0 
 "x_24"     16.0 
 "x_32"     14.0 
 "x_43"     20.0 
 "x_51"     48.0 
 "x_53"     14.0 
 "x_62"     46.0 
 "x_63"     10.0 
 "x_64"     12.0 
 "_"          "_"

### 7

In [99]:
ex7_S = [200, 1000, 500, 800, 400, 400, 200]
ex7_D = [400, 600, 2200]
M = 1000
ex7_C = [0 copy(M) copy(M);
    25 25.75 26.5;
    30 30.9 31.8;
    copy(M) 26 26.78;
    copy(M) 32 32.96;
    copy(M) copy(M) 29;
    copy(M) copy(M) 37]

7×3 Array{Float64,2}:
    0.0  1000.0   1000.0 
   25.0    25.75    26.5 
   30.0    30.9     31.8 
 1000.0    26.0     26.78
 1000.0    32.0     32.96
 1000.0  1000.0     29.0 
 1000.0  1000.0     37.0 

In [100]:
NCM(ex7_S, ex7_D, ex7_C)

Total Supply: 3500
Total Demand: 3200


7×4 Array{Float64,2}:
 200.0  NaN    NaN    NaN  
 200.0  600.0  200.0  NaN  
 NaN    NaN    500.0  NaN  
 NaN    NaN    800.0  NaN  
 NaN    NaN    400.0  NaN  
 NaN    NaN    300.0  100.0
 NaN    NaN    NaN    200.0

In [101]:
MCM(ex7_S, ex7_D, ex7_C)

Total Supply: 3500
Total Demand: 3200


7×4 Array{Float64,2}:
 200.0  NaN    NaN    NaN  
 200.0  500.0  NaN    300.0
 NaN    NaN    500.0  NaN  
 NaN    100.0  700.0  NaN  
 NaN    NaN    400.0  NaN  
 NaN    NaN    400.0  NaN  
 NaN    NaN    200.0  NaN  

In [102]:
Vogel(ex7_S, ex7_D, ex7_C)

Total Supply: 3500
Total Demand: 3200


7×4 Array{Float64,2}:
 200.0  NaN    NaN    NaN  
 200.0  NaN    800.0  NaN  
 NaN    300.0  200.0  NaN  
 NaN    NaN    800.0  NaN  
 NaN    300.0  NaN    100.0
 NaN    NaN    400.0  NaN  
 NaN    NaN    NaN    200.0

In [103]:
ex7_sol = GeneralSolver(ex7_S, ex7_D, ex7_C);

Total Supply: 3500
Total Demand: 3200


LoadError: InterruptException:

In [ ]:
ex7_sol[1]

### 8

In [26]:
ex8_S = [1, 1, 1, 1]
ex8_D = [2, 1, 1, 1]
M = 1000; 
ex8_C = -1000*[85 110 -copy(M) -copy(M);
    93 113 125 76; 
    97 -copy(M) 116 59; 
    -copy(M) -copy(M) 124 72]';

In [27]:
NCM(ex8_S, ex8_D, ex8_C)

Total Supply: 4
Total Demand: 5


5×4 Array{Float64,2}:
   1.0  NaN    NaN    NaN  
   1.0  NaN    NaN    NaN  
   0.0    1.0  NaN    NaN  
 NaN      0.0    1.0  NaN  
 NaN    NaN      0.0    1.0

In [28]:
MCM(ex8_S, ex8_D, ex8_C)

Total Supply: 4
Total Demand: 5


5×4 Array{Float64,2}:
   0.0  NaN      1.0  NaN  
   1.0    0.0  NaN    NaN  
 NaN      1.0  NaN    NaN  
   0.0  NaN    NaN      1.0
   1.0  NaN    NaN    NaN  

In [29]:
Vogel(ex8_S, ex8_D, ex8_C)

Total Supply: 4
Total Demand: 5


5×4 Array{Float64,2}:
 NaN    NaN      1.0  NaN  
   1.0  NaN    NaN    NaN  
 NaN    NaN    NaN      1.0
 NaN      1.0    0.0    0.0
   1.0  NaN      0.0  NaN  

In [30]:
ex8_sol = GeneralSolver(ex8_S, ex8_D, ex8_C);

Total Supply: 4
Total Demand: 5

Iterations: 125970



In [31]:
ex8_sol[2]

12×2 Array{Any,2}:
 "_"            "_"
 "Cost"  -407000.0 
 "_"            "_"
 "x_11"        0.0 
 "x_12"        0.0 
 "x_13"        1.0 
 "x_14"        0.0 
 "x_21"        1.0 
 "x_34"        1.0 
 "x_42"        1.0 
 "x_51"        1.0 
 "_"            "_"

### 9

In [44]:
ex9_S = [24/4, 4/4, 8/4, 4/4]
ex9_D = [20/4, 12/4, 8/2]
ex9_C = [6 15 68; 3 10 67; 0 12 70; 0 10 65]

4×3 Array{Int64,2}:
 6  15  68
 3  10  67
 0  12  70
 0  10  65

In [45]:
NCM(ex9_S, ex9_D, ex9_C)

Total Supply: 10.0
Total Demand: 12.0


5×3 Array{Float64,2}:
   5.0    1.0  NaN  
 NaN      1.0  NaN  
 NaN      1.0    1.0
 NaN    NaN      1.0
 NaN    NaN      2.0

In [47]:
ex9_sol = GeneralSolver(ex9_S, ex9_D, ex9_C)[1]

Total Supply: 10.0
Total Demand: 12.0

Iterations: 6435



Dict{Any,Any} with 3 entries:
  "Cost"       => 188.0
  "Value"      => [2.0, 2.0, 2.0, 1.0, 2.0, 1.0, 2.0]
  "Basic Pair" => String["x_11", "x_12", "x_13", "x_22", "x_31", "x_41", "x_53"]

<br>

- - -

<br>

# Triangularization

In [32]:
function make_triang(in_A)
    
    A = float(copy(in_A))
    
    m, n = size(A)
    left_vec = fill(NaN, m, 1)
    down_vec = fill(NaN, 1, n)
    
    counter = 0
    while count(.!isnan.(A)) > 0
        for i in 1:m
            if count(A[i,:] .!= 0) - count(isnan.(A[i,:])) == 1 
                counter += 1
                j = indmax(abs.(A[i,:]))
                down_vec[j] = counter
                left_vec[i] = counter
                A[i,:] .= NaN
                A[:,j] .= NaN
                break
            elseif count(A[i,:] .== 0) == count(.!isnan.(A[i,:])) && count(A[i,:] .== 0) > 0
                counter += 1
                j = indmax(abs.(A[i,:]))
                down_vec[j] = counter
                left_vec[i] = counter
                A[i,:] .= NaN
                A[:,j] .= NaN
                break                
            end
        end
    end
    
    for (index_i, i) in enumerate(left_vec), (index_j, j) in enumerate(down_vec)
        A[Int(i), Int(j)] = in_A[index_i, index_j]
    end
                                
    return A
end

make_triang (generic function with 1 method)

In [33]:
mat = [4 2 3 2 0; 0 2 0 0 0; 0 4 3 2 0; 1 4 5 0 0; 2 2 0 0 0]

5×5 Array{Int64,2}:
 4  2  3  2  0
 0  2  0  0  0
 0  4  3  2  0
 1  4  5  0  0
 2  2  0  0  0

In [34]:
make_triang(mat)

5×5 Array{Float64,2}:
 2.0  0.0  0.0  0.0  0.0
 2.0  2.0  0.0  0.0  0.0
 4.0  1.0  5.0  0.0  0.0
 2.0  4.0  3.0  2.0  0.0
 4.0  0.0  3.0  2.0  0.0

In [35]:
ex_mat = [1 2 0 1 0 2; 4 1 0 5 0 0; 0 0 0 4 0 0; 2 1 7 2 1 3; 2 3 2 0 0 3; 0 2 0 1 0 0]

6×6 Array{Int64,2}:
 1  2  0  1  0  2
 4  1  0  5  0  0
 0  0  0  4  0  0
 2  1  7  2  1  3
 2  3  2  0  0  3
 0  2  0  1  0  0

In [36]:
make_triang(ex_mat)

6×6 Array{Float64,2}:
 4.0  0.0  0.0  0.0  0.0  0.0
 1.0  2.0  0.0  0.0  0.0  0.0
 5.0  1.0  4.0  0.0  0.0  0.0
 1.0  2.0  1.0  2.0  0.0  0.0
 0.0  3.0  2.0  3.0  2.0  0.0
 2.0  1.0  2.0  3.0  7.0  1.0

In [37]:
make_triang(zeros(3,3))

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [38]:
response = Vogel(ex8_S, ex8_D, ex8_C);

Total Supply: 4
Total Demand: 5


In [39]:
response

5×4 Array{Float64,2}:
 NaN    NaN      1.0  NaN  
   1.0  NaN    NaN    NaN  
 NaN    NaN    NaN      1.0
 NaN      1.0    0.0    0.0
   1.0  NaN      0.0  NaN  

In [40]:
basis_vec = []
basis_order_vec = []
for (index, i) in enumerate(vec(response))
    if !isnan(i)
        push!(basis_vec, i)
        push!(basis_order_vec, index)
    end
end

In [41]:
basis_vec

8-element Array{Any,1}:
 1.0
 1.0
 1.0
 1.0
 0.0
 0.0
 1.0
 0.0

In [42]:
basis_order_vec

8-element Array{Any,1}:
  2
  5
  9
 11
 14
 15
 18
 19

<br>