In [1]:
using Interact
using Gadfly
using DataFrames
using Combinatorics

# Experimenting with Matrices

Taken from [here](http://stanford.edu/class/ee103/julia_slides/julia_matrices_slides.pdf)

## Basics

In [2]:
A = [2 -4 8.2; -5.5 3.5 63]

2×3 Array{Float64,2}:
  2.0  -4.0   8.2
 -5.5   3.5  63.0

In [3]:
size(A)

(2, 3)

In [4]:
A_rows = A[1]
A_columns = A[2]

-5.5

In [5]:
# Ai,j is found with A[i,y]. For example:
-2*A[1,1] == A[1,2]

true

In [6]:
# Moreover, can use ranges
# A[1:2,1:3] is 2 × 3 submatrix, or slice A1:2,1:3

A[1:2,2:3]

2×2 Array{Float64,2}:
 -4.0   8.2
  3.5  63.0

In [7]:
# : selects all elements along that dimension, for example
# A[:,3] is third column
# A[2,:] is second row

A[:,3]
A[2,:]

3-element Array{Float64,1}:
 -5.5
  3.5
 63.0

In [8]:
# A[:] stacks the columns of A as a vector (column-major order)

vector_column_major_order = A[:]

6-element Array{Float64,1}:
  2.0
 -5.5
 -4.0
  3.5
  8.2
 63.0

In [9]:
# A’[:] stacks the rows of A as a vector (row-major order)

vector_row_major_order = A'[:]

6-element Array{Float64,1}:
  2.0
 -4.0
  8.2
 -5.5
  3.5
 63.0

---

## Block Matrices

$$ \textbf{X} =
\begin{pmatrix}
\text{A} & \text{B}\\
\text{C} & \text{D}\\
\end{pmatrix} $$

Where $A$, $B$, $C$, and $D$ are matrices formed with:

`X = [A B; C D]`

Note that the usual rules governing dimensions of $A$, $B$, $C$, and $D$ apply!

In [10]:
# A is currently 2 x 3, so B needs to be 3 x 2
B = [1 1 -2; 3 1.5 4]

2×3 Array{Float64,2}:
 1.0  1.0  -2.0
 3.0  1.5   4.0

In [11]:
# Let's make C a 2 x 2 matrix
C = [1 0; 0 1]

2×2 Array{Int64,2}:
 1  0
 0  1

In [12]:
# Let's make D a 2 x 4 matrix
D = [0 1 5 -3.5; -2 8 0.5 2]

2×4 Array{Float64,2}:
  0.0  1.0  5.0  -3.5
 -2.0  8.0  0.5   2.0

In [13]:
# Let's make our X matrix now!
X = [A B; C D]

4×6 Array{Float64,2}:
  2.0  -4.0   8.2  1.0  1.0  -2.0
 -5.5   3.5  63.0  3.0  1.5   4.0
  1.0   0.0   0.0  1.0  5.0  -3.5
  0.0   1.0  -2.0  8.0  0.5   2.0

- - -

## Other useful matrices in Julia

$\mathbf{0}_{m×n}$ is `zeros(m,n)`

$(m\ x\ n)$ matrix with all entries 1 is `ones(m,n)`

$\mathbf{I}_{n×n}$ identity matrix is `eye(n)`

$\mathbf{diag}(x)$ is `diagm(x)` (where $\mathbf{x}$ is a vector)

In [14]:
zeros(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [15]:
zeros(2)

2-element Array{Float64,1}:
 0.0
 0.0

In [16]:
zeros(1,3)

1×3 Array{Float64,2}:
 0.0  0.0  0.0

In [17]:
ones(3,3)

3×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [18]:
eye(2)

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

In [19]:
# Given some vector, for example, let's diagonalize it!
# Note that `diagm(ones(3,1))` wont work! See below:
diagm(ones(3))

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [20]:
# What's the difference?
size(ones(3,1))

(3, 1)

In [21]:
# [continued] What's the difference?
size(ones(3))

(3,)

---

## Transpose, matrix addition, and multiplication

$A^T$ is written `A’` (single quote mark)


$+\ /\ -$ are used for matrix addition/substraction, though note that matrices must have the same size. For example:

$$ \left[ \begin{array}{cc} 4 & 7\\ -10.6 & 89.8\end{array} \right] +  \left[ \begin{array}{cc} 19 & -34.7\\ 20 & 1\end{array} \right]$$

... is written `[4.0 7; -10.6 89.8] + [19 -34.7; 20 1]`

To add just do this `[4.0 7; -10.6 89.8] * [19 -34.7; 20 1]` or this `A^k` for $\mathbf{A}^k$, as long as $\mathbf{A}$ is a square matrix, i.e. of size $(n\ x\ n)$.

In [22]:
# Let's try!
M_add = [4.0 7; -10.6 89.8] + [19 -34.7; 20 1]

2×2 Array{Float64,2}:
 23.0  -27.7
  9.4   90.8

In [23]:
# Similarly, to multiple:
M_multiply = [4.0 7; -10.6 89.8] * [19 -34.7; 20 1]

2×2 Array{Float64,2}:
  216.0  -131.8 
 1594.6   457.62

In [24]:
println("Matrix has size ", size(M_add), "; hence we can multiply it by itself, in order to get ", M_add^2)

Matrix has size (2, 2); hence we can multiply it by itself, in order to get [268.62 -3152.26; 1069.72 7984.26]


---

## Other functions

Sum of entries of a matrix: `sum(A)`

Average of entries of a matrix: `mean(A)`

`max(A,B)` and `min(A,B)` finds the element-wise max and min respectively  
* Please note that the arguments must have the same size unless one is a scalar

`norm(A)` is not what you might think...

$$ \Big(\sum\nolimits_{i,\ j} \vcenter{\large{\mathit{A_{i,\ j}^2}}}\Big) $$


\begin{eqnarray} \tag{$\dagger$}
y &=& (x-1)^2 \\
  &=& (x-1)(x-1) \\
  &=& x^2 - 2x + 1
\end{eqnarray}

$$
a_1 = b_1 + c_1 \\
a_2 = b_2 + c_2 + d_2
$$

\begin{align}
a_1 & = & b_1 + c_1 \\
a_2 & = & b_2 + c_2 + d_2
\end{align}

In [95]:
G = [1 2; 0 0]

2×2 Array{Int64,2}:
 1  2
 0  0

In [96]:
norm(G)

2.23606797749979

In [97]:
norm(G[:])

2.23606797749979

In [98]:
vecnorm(G)

2.23606797749979

$$ A = \pmatrix{
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn} \\
} $$

---

## The Simplex Machine for Robots

The initial setup: